#!/usr/bin/env bash
# scripts/deploy/preflight.sh — Phase 10 Wave 0 preflight probe for n8n-ia-vm.
#
# Idempotent operator-runnable script. Runs 5 sections gated by log_section
# banners; populates the capacity-observed file in this phase directory.
#
# Sections:
#   1) Connectivity                    — `ssh n8n-ia-vm 'echo ok'` returns "ok"
#   2) Capacity snapshot               — free -h / df -h / docker info|grep swarm /
#                                        ifconfig.io egress IP. Aborts if disk > 80%
#                                        OR egress IP != 162.55.92.154.
#   3) Intra overlay attachability     — Assumption A4. `docker network inspect intra -f
#                                        '{{.Attachable}}'` must print true (RESEARCH
#                                        Pitfall 1).
#   4) Internal-Traefik discovery probe — Open Question 2 / Assumption A2. Deploys an
#                                        ephemeral hello-world container on `intra`
#                                        overlay with Traefik labels; greps Traefik
#                                        Swarm-mode logs for router-added evidence.
#                                        If FAIL → operator must switch traefik-internal
#                                        to dual-provider (--providers.docker=true
#                                        alongside --providers.docker.swarmMode=true)
#                                        per RESEARCH Open Question 2 option B.
#   4b) Dashboard health probe         — Phase 11 Plan 11-05 (Gemini suggestion).
#                                        curl -fs $DASHBOARD_HEALTH_URL (Better Auth
#                                        /api/auth/ok endpoint chosen + verified
#                                        2026-05-27). Non-200 fails the preflight so
#                                        an SSO hardening regression cannot silently
#                                        break the operator-facing dashboard.
#   5) GHA runners health              — Assumption A7. `gh run list` confirms a recent
#                                        build OR explicitly flags "no recent runs" so
#                                        operator can confirm runner pool.
#
# Exit codes:
#   0 — all probes PASS, capacity-observed file populated
#   1 — connectivity FAIL (ssh n8n-ia-vm unreachable)
#   2 — disk > 80% OR egress IP mismatch (capacity gate per RESEARCH Pitfall 6)
#   3 — internal-Traefik discovery probe FAIL (fallback required)
#   4 — intra overlay missing or not attachable (Pitfall 1)
#   5 — dashboard health probe FAIL (non-200 at $DASHBOARD_HEALTH_URL — 11-05)
#
# IMPORTANT: Plan 10-01 (autonomous) CREATES this script but does NOT execute
# the live SSH probes — those require live infra credentials and operator
# session. The actual capacity capture happens during Plan 10-06 HUMAN-UAT
# Gate B. This is intentional: autonomous executor has no SSH session.
#
# Usage:
#   ./scripts/deploy/preflight.sh
#
# Side effects:
#   - Writes/overwrites
#     .planning/phases/10-prod-deploy-ai-gateway/10-01-CAPACITY-OBSERVED.md
#     with timestamped probe output and PASS/FAIL per section.
#   - Spawns + tears down ephemeral container `preflight-hello` on n8n-ia-vm
#     (cleanup is unconditional, runs even on failure).

set -euo pipefail

# --- defaults -------------------------------------------------------------
N8N_HOST=${N8N_HOST:-n8n-ia-vm}
EXPECTED_EGRESS_IP=${EXPECTED_EGRESS_IP:-162.55.92.154}
DISK_CRITICAL_PCT=${DISK_CRITICAL_PCT:-80}
PHASE_DIR=${PHASE_DIR:-.planning/phases/10-prod-deploy-ai-gateway}
CAPACITY_FILE="${PHASE_DIR}/10-01-CAPACITY-OBSERVED.md"
EPHEMERAL_NAME="preflight-hello"

# --- helpers --------------------------------------------------------------
log_section() {
  printf '\n============================================================\n%s\n============================================================\n' "$*"
}

log() {
  printf '[%s] %s\n' "$(date -Iseconds)" "$*" >&2
}

append_capacity() {
  printf '%s\n' "$*" >> "$CAPACITY_FILE"
}

# Tear down the ephemeral hello container regardless of outcome.
cleanup_ephemeral() {
  log "cleanup: removing ephemeral ${EPHEMERAL_NAME} container (if present)"
  ssh "$N8N_HOST" "docker rm -f ${EPHEMERAL_NAME} >/dev/null 2>&1 || true"
}
trap cleanup_ephemeral EXIT

# --- preconditions --------------------------------------------------------
if [ ! -d "$PHASE_DIR" ]; then
  log "FATAL: phase directory not found: $PHASE_DIR"
  exit 1
fi

# Initialise capacity file with a timestamp banner (overwrites prior content).
TIMESTAMP=$(date -Iseconds)
cat > "$CAPACITY_FILE" <<EOF
---
phase: 10
plan: 01
captured: "${TIMESTAMP}"
host: ${N8N_HOST}
expected_egress_ip: ${EXPECTED_EGRESS_IP}
---

# Phase 10-01 — Live capacity probe (n8n-ia-vm)

Generated by \`scripts/deploy/preflight.sh\` on ${TIMESTAMP}.
Each section header below maps 1:1 to a probe in the script.

EOF

# --- 1) Connectivity ------------------------------------------------------
log_section "1) Connectivity"
append_capacity "## 1) Connectivity"
append_capacity ""

if OUT=$(ssh -o BatchMode=yes -o ConnectTimeout=10 "$N8N_HOST" 'echo ok' 2>&1); then
  if [ "$OUT" = "ok" ]; then
    log "PASS — ssh ${N8N_HOST} returns ok"
    append_capacity '\`\`\`'
    append_capacity "ssh ${N8N_HOST} 'echo ok' → ok"
    append_capacity '\`\`\`'
    append_capacity ""
    append_capacity "**Status:** PASS"
  else
    log "FAIL — unexpected output: $OUT"
    append_capacity "**Status:** FAIL — unexpected output: ${OUT}"
    exit 1
  fi
else
  log "FAIL — ssh ${N8N_HOST} unreachable: $OUT"
  append_capacity "**Status:** FAIL — ssh unreachable: ${OUT}"
  exit 1
fi

# --- 2) Capacity snapshot -------------------------------------------------
log_section "2) Capacity snapshot"
append_capacity ""
append_capacity "## 2) Capacity snapshot"
append_capacity ""

CAPACITY_RAW=$(ssh "$N8N_HOST" '
  echo "--- free -h ---"
  free -h
  echo
  echo "--- df -h / ---"
  df -h /
  echo
  echo "--- df -h /var/lib/docker ---"
  df -h /var/lib/docker
  echo
  echo "--- docker info (swarm + cpus) ---"
  docker info 2>/dev/null | grep -iE "swarm|cpus"
  echo
  echo "--- egress IP (curl ifconfig.io) ---"
  curl -s --max-time 5 ifconfig.io
  echo
' 2>&1)

append_capacity '\`\`\`'
append_capacity "$CAPACITY_RAW"
append_capacity '\`\`\`'
append_capacity ""

# Parse disk percentage from `df -h /` line.
DISK_PCT=$(printf '%s\n' "$CAPACITY_RAW" \
  | awk '/--- df -h \/ ---/{flag=1;next} flag && /\/$/ {gsub("%",""); print $5; exit}')
if [ -z "$DISK_PCT" ]; then
  log "WARN — could not parse disk percentage; skipping gate"
else
  log "disk / usage = ${DISK_PCT}%"
  if [ "$DISK_PCT" -gt "$DISK_CRITICAL_PCT" ]; then
    log "FAIL — DISK CRITICAL — run docker image prune first"
    append_capacity "**Disk gate:** FAIL — / at ${DISK_PCT}% > ${DISK_CRITICAL_PCT}% — run \`docker image prune -af\` first"
    exit 2
  fi
  append_capacity "**Disk gate:** PASS — / at ${DISK_PCT}% ≤ ${DISK_CRITICAL_PCT}%"
fi

# Parse egress IP — last non-empty line after the `--- egress IP ---` banner.
EGRESS_IP=$(printf '%s\n' "$CAPACITY_RAW" \
  | awk '/--- egress IP/{flag=1;next} flag && NF>0 {print; exit}')
log "egress IP from VM 101 = ${EGRESS_IP}"
if [ "$EGRESS_IP" != "$EXPECTED_EGRESS_IP" ]; then
  log "FAIL — egress IP ${EGRESS_IP} != ${EXPECTED_EGRESS_IP} (DO Trusted Sources mismatch — RESEARCH How To #3)"
  append_capacity "**Egress gate:** FAIL — observed ${EGRESS_IP} != expected ${EXPECTED_EGRESS_IP} (DO Postgres Trusted Sources would reject this IP)"
  exit 2
fi
append_capacity "**Egress gate:** PASS — egress IP ${EGRESS_IP} matches DO Trusted Sources entry ${EXPECTED_EGRESS_IP}"
append_capacity ""

# --- 3) Intra overlay attachability --------------------------------------
log_section "3) Intra overlay attachability"
append_capacity "## 3) Intra overlay attachability"
append_capacity ""

if ATTACHABLE=$(ssh "$N8N_HOST" "docker network inspect intra -f '{{.Attachable}}'" 2>&1); then
  log "intra attachable = ${ATTACHABLE}"
  if [ "$ATTACHABLE" = "true" ]; then
    append_capacity '\`\`\`'
    append_capacity "docker network inspect intra -f '{{.Attachable}}' → true"
    append_capacity '\`\`\`'
    append_capacity ""
    append_capacity "**Status:** PASS — Assumption A4 verified; standalone-compose containers can join the Swarm overlay"
  else
    log "FAIL — intra overlay is not attachable (Attachable=${ATTACHABLE})"
    append_capacity "**Status:** FAIL — intra Attachable=${ATTACHABLE} (Pitfall 1 reminder: prod compose declares networks.intra.external: true and requires attachable=true)"
    exit 4
  fi
else
  log "FAIL — intra overlay missing (Pitfall 1 reminder: rename worker_intra → intra; create overlay if absent)"
  append_capacity "**Status:** FAIL — \`docker network inspect intra\` errored: ${ATTACHABLE}"
  append_capacity ""
  append_capacity "Pitfall 1 reminder: gateway/docker-compose.prod.yml declares \`networks.intra.external: true\` so the network MUST exist on n8n-ia-vm before \`docker compose up -d\`. The Swarm template referenced \`worker_intra\` (which does NOT exist on n8n-ia-vm) — that rename is the whole point of Wave 0."
  exit 4
fi
append_capacity ""

# --- 4) Internal-Traefik discovery probe ---------------------------------
log_section "4) Internal-Traefik discovery probe"
append_capacity "## 4) Internal-Traefik discovery probe"
append_capacity ""

log "spawning ephemeral ${EPHEMERAL_NAME} container on intra with Traefik labels"
ssh "$N8N_HOST" "docker rm -f ${EPHEMERAL_NAME} >/dev/null 2>&1 || true"
ssh "$N8N_HOST" "docker run -d --rm --name ${EPHEMERAL_NAME} \
  --network intra \
  --label traefik.enable=true \
  --label 'traefik.http.routers.preflight_hello.rule=Host(\`preflight-hello.invalid\`)' \
  --label traefik.http.services.preflight_hello.loadbalancer.server.port=80 \
  nginxdemos/hello:plain-text >/dev/null"

log "waiting 3s for Traefik to observe the container"
sleep 3

TRAEFIK_SVC=$(ssh "$N8N_HOST" "docker service ls --filter name=traefik-internal --format '{{.Name}}'" 2>/dev/null | head -1)
if [ -z "$TRAEFIK_SVC" ]; then
  log "FAIL — could not locate traefik-internal Swarm service"
  append_capacity "**Status:** FAIL — Swarm service \`traefik-internal*\` not found on n8n-ia-vm"
  exit 3
fi
log "found Traefik Swarm service: ${TRAEFIK_SVC}"

TRAEFIK_LOG=$(ssh "$N8N_HOST" "docker service logs --since 60s ${TRAEFIK_SVC} 2>&1" || true)
if printf '%s\n' "$TRAEFIK_LOG" | grep -qiE 'preflight[_-]?hello.*(router added|added router)'; then
  log "PASS — Traefik observed ephemeral container via Swarm provider"
  append_capacity '\`\`\`'
  append_capacity "$(printf '%s\n' "$TRAEFIK_LOG" | grep -i preflight | head -10)"
  append_capacity '\`\`\`'
  append_capacity ""
  append_capacity "**Status:** PASS — Open Question 2 / Assumption A2 verified. Standalone-compose containers on the intra overlay are discoverable by the Swarm-provider internal Traefik."
elif printf '%s\n' "$TRAEFIK_LOG" | grep -qi preflight; then
  log "PARTIAL — Traefik mentioned preflight_hello but no router-added match"
  append_capacity '\`\`\`'
  append_capacity "$(printf '%s\n' "$TRAEFIK_LOG" | grep -i preflight | head -10)"
  append_capacity '\`\`\`'
  append_capacity ""
  append_capacity "**Status:** PARTIAL — preflight_hello mentioned in Traefik logs but no router-added pattern. Operator review required before Wave 0 sign-off."
  exit 3
else
  log "FAIL — Traefik did not discover the standalone container (FALLBACK REQUIRED)"
  append_capacity "**Status:** FAIL — Traefik Swarm provider did not discover the standalone container."
  append_capacity ""
  append_capacity "**FALLBACK REQUIRED:** switch traefik-internal to dual-provider — add \`--providers.docker=true\` alongside \`--providers.docker.swarmMode=true\` per RESEARCH Open Question 2 option B. Plan 10-02 cannot proceed until operator remediates."
  exit 3
fi
append_capacity ""

# --- 4b) Dashboard health probe (Phase 11 Plan 11-05 — Gemini suggestion) ---
# Endpoint chosen: /api/auth/ok — Better Auth's built-in HIDE_METADATA health
# route (verified 2026-05-27 against better-auth ~1.4.18 source at
# node_modules/better-auth/dist/api/routes/ok.mjs:4-25; returns {"ok": true}
# with HTTP 200 when the auth handler is reachable). Fallback list if the
# installed Better Auth version drops /ok in a future major: /api/auth/get-session
# (anonymous returns 200 with null body), /health, root /. The dashboard
# at /api/auth/[...all]/route.ts (toNextJsHandler(auth)) mounts the catch-all.
# Fail-fast on non-200 so an SSO hardening regression cannot silently break
# the operator-facing dashboard surface during prod deploy preflight.
log_section "4b) Dashboard health probe"
append_capacity ""
append_capacity "## 4b) Dashboard health probe"
append_capacity ""

DASHBOARD_HEALTH_URL=${DASHBOARD_HEALTH_URL:-https://ai-dashboard.converse-ai.app/api/auth/ok}
log "probing dashboard health: $DASHBOARD_HEALTH_URL"

if DASHBOARD_HTTP_CODE=$(curl -fs -o /tmp/dashboard-health-status -w "%{http_code}" \
      --max-time 15 "$DASHBOARD_HEALTH_URL" 2>&1); then
  if [ "$DASHBOARD_HTTP_CODE" = "200" ]; then
    log "PASS — dashboard health OK ($DASHBOARD_HTTP_CODE) at $DASHBOARD_HEALTH_URL"
    append_capacity '\`\`\`'
    append_capacity "curl -fs $DASHBOARD_HEALTH_URL → $DASHBOARD_HTTP_CODE"
    append_capacity '\`\`\`'
    append_capacity ""
    append_capacity "**Status:** PASS — dashboard /api/auth/ok returned 200"
  else
    log "FATAL — dashboard health probe returned non-200: $DASHBOARD_HTTP_CODE at $DASHBOARD_HEALTH_URL"
    append_capacity "**Status:** FATAL — dashboard returned ${DASHBOARD_HTTP_CODE} (expected 200) at ${DASHBOARD_HEALTH_URL}"
    exit 5
  fi
else
  log "FATAL — dashboard health probe failed (curl error) for $DASHBOARD_HEALTH_URL: $DASHBOARD_HTTP_CODE"
  append_capacity "**Status:** FATAL — dashboard health probe failed for ${DASHBOARD_HEALTH_URL} (curl error: ${DASHBOARD_HTTP_CODE})"
  exit 5
fi
append_capacity ""

# --- 5) GHA runners health -----------------------------------------------
log_section "5) GHA runners health"
append_capacity "## 5) GHA runners health"
append_capacity ""

if command -v gh >/dev/null 2>&1; then
  if GH_OUT=$(gh run list --limit 1 --workflow build-gateway.yml --json status,conclusion,createdAt 2>&1); then
    log "gh run list: ${GH_OUT}"
    append_capacity '\`\`\`json'
    append_capacity "$GH_OUT"
    append_capacity '\`\`\`'
    append_capacity ""
    append_capacity "**Status:** PASS — gh CLI returned at least one workflow run record. Operator inspects above for recency."
  else
    log "WARN — gh run list failed: ${GH_OUT}"
    append_capacity "**Status:** WARN — gh run list failed: ${GH_OUT}"
    append_capacity ""
    append_capacity "Operator must confirm runner pool health manually before triggering the \`v1.0.0\` tag push."
  fi
else
  log "WARN — gh CLI not on PATH; skipping runners check"
  append_capacity "**Status:** SKIPPED — gh CLI not on PATH on the host running preflight.sh."
fi
append_capacity ""

log_section "DONE — preflight PASS"
append_capacity "---"
append_capacity ""
append_capacity "_Generated by \`scripts/deploy/preflight.sh\` at ${TIMESTAMP}._"
log "capacity report written: ${CAPACITY_FILE}"

exit 0
