/**
 * Better Auth Drizzle schema — CLI-canonical (Phase 11 [reviews HIGH #3];
 * Phase 13 D-01/D-02 admin-plugin columns).
 *
 * This file is REGENERATED by `bunx @better-auth/cli@latest generate
 * --output src/lib/schema.ts --yes` (run from `dashboard/`). Do NOT
 * edit the table definitions by hand — any local change WILL be
 * overwritten on the next regen (this very header is re-prepended by
 * hand after each regen, since the generator owns the file body). To
 * add/modify auth tables, change the Better Auth plugin config in
 * `src/lib/auth.ts` and re-run `generate`.
 *
 * Phase 13: the `admin` plugin (auth.ts) added `role`/`banned`/
 * `banReason`/`banExpires` to the `user` table and `impersonatedBy` to
 * `session` — they appear below automatically after regen.
 *
 * The CUSTOM `admin_audit_log` table is NOT here — the generator would
 * drop it (13-RESEARCH Pitfall 1). It lives in `schema-custom.ts` and is
 * merged into the drizzle client in `db.ts`; `drizzle.config.ts` globs
 * `./src/lib/schema*.ts` so `drizzle-kit push` migrates both.
 *
 * Migration workflow (Drizzle adapter — the `migrate` CLI command does
 * NOT support Drizzle; rejected at runtime with a clear error):
 *
 *   1. `bunx @better-auth/cli@latest generate --output src/lib/schema.ts --yes`
 *   2. re-prepend this header block
 *   3. `bunx drizzle-kit push` (uses dashboard/drizzle.config.ts)
 *
 * Lives in a dedicated database (`bd_ai_dashboard_staging` for the
 * staging rehearsal target, `bd_ai_dashboard_prod` for prod), in the
 * `public` schema — isolated from `ai_gateway` per 07-RESEARCH Pitfall 7.
 */
import { relations } from "drizzle-orm";
import { pgTable, text, timestamp, boolean, index } from "drizzle-orm/pg-core";

export const user = pgTable("user", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: boolean("email_verified").default(false).notNull(),
  image: text("image"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at")
    .defaultNow()
    .$onUpdate(() => /* @__PURE__ */ new Date())
    .notNull(),
  twoFactorEnabled: boolean("two_factor_enabled").default(false),
  role: text("role"),
  banned: boolean("banned").default(false),
  banReason: text("ban_reason"),
  banExpires: timestamp("ban_expires"),
});

export const session = pgTable(
  "session",
  {
    id: text("id").primaryKey(),
    expiresAt: timestamp("expires_at").notNull(),
    token: text("token").notNull().unique(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .$onUpdate(() => /* @__PURE__ */ new Date())
      .notNull(),
    ipAddress: text("ip_address"),
    userAgent: text("user_agent"),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    impersonatedBy: text("impersonated_by"),
    twoFactorVerified: boolean("two_factor_verified").default(false),
  },
  (table) => [index("session_userId_idx").on(table.userId)],
);

export const account = pgTable(
  "account",
  {
    id: text("id").primaryKey(),
    accountId: text("account_id").notNull(),
    providerId: text("provider_id").notNull(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    accessToken: text("access_token"),
    refreshToken: text("refresh_token"),
    idToken: text("id_token"),
    accessTokenExpiresAt: timestamp("access_token_expires_at"),
    refreshTokenExpiresAt: timestamp("refresh_token_expires_at"),
    scope: text("scope"),
    password: text("password"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .$onUpdate(() => /* @__PURE__ */ new Date())
      .notNull(),
  },
  (table) => [index("account_userId_idx").on(table.userId)],
);

export const verification = pgTable(
  "verification",
  {
    id: text("id").primaryKey(),
    identifier: text("identifier").notNull(),
    value: text("value").notNull(),
    expiresAt: timestamp("expires_at").notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .defaultNow()
      .$onUpdate(() => /* @__PURE__ */ new Date())
      .notNull(),
  },
  (table) => [index("verification_identifier_idx").on(table.identifier)],
);

export const twoFactor = pgTable(
  "two_factor",
  {
    id: text("id").primaryKey(),
    secret: text("secret").notNull(),
    backupCodes: text("backup_codes").notNull(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
  },
  (table) => [
    index("twoFactor_secret_idx").on(table.secret),
    index("twoFactor_userId_idx").on(table.userId),
  ],
);

export const userRelations = relations(user, ({ many }) => ({
  sessions: many(session),
  accounts: many(account),
  twoFactors: many(twoFactor),
}));

export const sessionRelations = relations(session, ({ one }) => ({
  user: one(user, {
    fields: [session.userId],
    references: [user.id],
  }),
}));

export const accountRelations = relations(account, ({ one }) => ({
  user: one(user, {
    fields: [account.userId],
    references: [user.id],
  }),
}));

export const twoFactorRelations = relations(twoFactor, ({ one }) => ({
  user: one(user, {
    fields: [twoFactor.userId],
    references: [user.id],
  }),
}));
